name: inventory_application
description: A uniform inventory system app
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  cupertino_icons: ^1.0.5
  shared_preferences: ^2.1.0
  google_fonts: ^6.2.1
  charts_flutter_new: ^0.12.0
  fl_chart: ^0.68.0
  firebase_core: ^3.15.2
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.4.0
  google_sign_in: ^6.1.5
  http: ^1.1.0
  qr_flutter: ^4.1.0
  mailer: ^6.1.1
  path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
