// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfppfpgtw3zG_ueshLFkecChTpqZTRCos',
    appId: '1:533072990076:web:845172bed03cc7e8759ef9',
    messagingSenderId: '533072990076',
    projectId: 'siasu-223bb',
    authDomain: 'siasu-223bb.firebaseapp.com',
    storageBucket: 'siasu-223bb.firebasestorage.app',
    measurementId: 'G-1DZFV1CT80',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcWNqkTB30DTPaNJ3tQSUd0zpN_j9RBj0',
    appId: '1:533072990076:android:cc8ea113ec193384759ef9',
    messagingSenderId: '533072990076',
    projectId: 'siasu-223bb',
    storageBucket: 'siasu-223bb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBr1zBJWp18ExAXQP8ADY0tPNG7Iq3nKp4',
    appId: '1:533072990076:ios:aad962038e62194f759ef9',
    messagingSenderId: '533072990076',
    projectId: 'siasu-223bb',
    storageBucket: 'siasu-223bb.firebasestorage.app',
    iosClientId: '533072990076-om257nb1lphoks97qmle9aan4k7qks2e.apps.googleusercontent.com',
    iosBundleId: 'com.example.inventoryApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBr1zBJWp18ExAXQP8ADY0tPNG7Iq3nKp4',
    appId: '1:533072990076:ios:aad962038e62194f759ef9',
    messagingSenderId: '533072990076',
    projectId: 'siasu-223bb',
    storageBucket: 'siasu-223bb.firebasestorage.app',
    iosClientId: '533072990076-om257nb1lphoks97qmle9aan4k7qks2e.apps.googleusercontent.com',
    iosBundleId: 'com.example.inventoryApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfppfpgtw3zG_ueshLFkecChTpqZTRCos',
    appId: '1:533072990076:web:625a886c1588d3a8759ef9',
    messagingSenderId: '533072990076',
    projectId: 'siasu-223bb',
    authDomain: 'siasu-223bb.firebaseapp.com',
    storageBucket: 'siasu-223bb.firebasestorage.app',
    measurementId: 'G-T6QFJQRYZG',
  );
}
