// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCi1HCrGTzTkk48L1wnIRwkruV442jIvqI',
    appId: '1:427335898236:web:f0c4810749aa6dd0d525f9',
    messagingSenderId: '427335898236',
    projectId: 'inventoryapp-f0e37',
    authDomain: 'inventoryapp-f0e37.firebaseapp.com',
    storageBucket: 'inventoryapp-f0e37.firebasestorage.app',
    measurementId: 'G-P8V3EDNST4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwH0LCpM7TIVp8tYflYdo6sTrzKd3hDlE',
    appId: '1:427335898236:android:4bdebc0db7d3ec12d525f9',
    messagingSenderId: '427335898236',
    projectId: 'inventoryapp-f0e37',
    storageBucket: 'inventoryapp-f0e37.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSftqI-PD3hOphOECnmpgQzk3gN9qFfI8',
    appId: '1:427335898236:ios:8f0b6ffc562f017ad525f9',
    messagingSenderId: '427335898236',
    projectId: 'inventoryapp-f0e37',
    storageBucket: 'inventoryapp-f0e37.firebasestorage.app',
    iosBundleId: 'com.example.inventoryApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSftqI-PD3hOphOECnmpgQzk3gN9qFfI8',
    appId: '1:427335898236:ios:8f0b6ffc562f017ad525f9',
    messagingSenderId: '427335898236',
    projectId: 'inventoryapp-f0e37',
    storageBucket: 'inventoryapp-f0e37.firebasestorage.app',
    iosBundleId: 'com.example.inventoryApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCi1HCrGTzTkk48L1wnIRwkruV442jIvqI',
    appId: '1:427335898236:web:0ac36915e20565a9d525f9',
    messagingSenderId: '427335898236',
    projectId: 'inventoryapp-f0e37',
    authDomain: 'inventoryapp-f0e37.firebaseapp.com',
    storageBucket: 'inventoryapp-f0e37.firebasestorage.app',
    measurementId: 'G-NFPREKL7QG',
  );
}
